### ISSUE TITLE
ClassFraction:dividir

### ISSUE THREAD

**Issue by raquelsr** [raquelsr/IWVG.SwC.Raquel#4]
Añadir método para dividir fracciones.

> (Recuerda que el plazo de entrega es el viernes.)

[Más información](../wiki/Documentación#clase-fraction---método-para-dividir-fracciones)

**Comment by joaquinz916** [comment]
Tengo una duda, al decir dividir fracciones el resultado debe devolver tambien una fraccion, o puede ser un número decimal?

**Comment by raquelsr** [comment]
Es indiferente. Como prefiera y resulte más fácil al programador.

**Comment by joaquinz916** [comment]
Funcionalidad y pruebas implementadas, ticket cerrado.
