### ISSUE TITLE
TestFraction:getMayor

### ISSUE THREAD

**Issue by raquelsr** [raquelsr/IWVG.SwC.Raquel#7]
Mejorar la cobertura del test en la clase Fraction para el método getMayor(), ya que ha bajado la calidad en sonar. 
Para ello, crea una nueva rama con el número de este nuevo ticket.

![captura de pantalla 2017-09-19 a las 19 34 11](https://user-images.githubusercontent.com/17765192/30606538-4f319f00-9d72-11e7-86c1-f6cc0b2246a2.png)
![captura de pantalla 2017-09-19 a las 19 30 25](https://user-images.githubusercontent.com/17765192/30606539-4f5bef6c-9d72-11e7-8067-48518b4d0668.png)

**Comment by AlbertoNitro** [comment]
Actualizacion sobre las pruebas realizada. Cierro ticket.
