### ISSUE TITLE
ClassDecimalCollection:media

### ISSUE THREAD

**Issue by raquelsr** [raquelsr/IWVG.SwC.Raquel#8]
Mejorar el método media de la clase DecimalCollection ya que no pasa correctamente el sonar por falta de calidad. En las imágenes se adjuntan las mejoras que hay que realizar: 
- Devolver directamente el resultado de la media (sin necesidad de crear variable).
- Crear una constante de "Empty Collection" y utilizarla para evitar la duplicidad del código.
Para más información consulta el [enlace a sonar](https://sonarcloud.io/project/issues?id=raquelsr%3AIWVG.SwC.Raquel&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL)

Tener en cuenta también que hay que mejorar el test para no reducir la cobertura, ya que hay que comprobar también el assert. Para hacer estas mejoras crear una rama nueva con el número de este ticket.

![captura de pantalla 2017-09-20 a las 17 56 24](https://user-images.githubusercontent.com/17765192/30654399-0b8ac058-9e2e-11e7-89cc-d7a9ef569032.png)
![captura de pantalla 2017-09-20 a las 17 57 35](https://user-images.githubusercontent.com/17765192/30654401-0b93c8ba-9e2e-11e7-8d54-1b6faed16fb6.png)
![captura de pantalla 2017-09-20 a las 17 59 26](https://user-images.githubusercontent.com/17765192/30654400-0b92703c-9e2e-11e7-92e4-290a4c04b9e4.png)

**Comment by joaquinz916** [comment]
Pasado el test de calidad de Sonar, ticket cerrado.
